site_name: Automation for OpenShift on IBM Power 
site_url: https://example.com/foo/

nav:
    - Home: index.md
    - Introduction: introduction.md
    - OCS-UPI-KVM: ocs_kvm.md
    - OCP4-UPI-PowerVS: powervs.md
    - OCP4-UPI-KVM: ocp_kvm.md
    - OCP4-UPI-PowerVM: powervm.md
    - PowerVS_Automation: automation.md
    - OCP4-Playbooks: playbook.md
    - Terraform-Provider-IBM: terraform.md
theme: readthedocs
